/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DrawingToolPanel.java
 *
 * Created on Aug 27, 2011, 11:12:41 AM
 */
package buckley.DrawingTool.gui;

import buckley.DrawingTool.interfaces.Tool;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;

/**
 *
 * @author Thunder
 */
public class DrawingToolPanel extends javax.swing.JPanel {
    
    /** Creates new form DrawingToolPanel */
    public DrawingToolPanel() {
        //add instance of each tool
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolSelectorPanel = new javax.swing.JPanel();
        toolSelectorLabel = new javax.swing.JLabel();
        toolSelectorComboBox = new javax.swing.JComboBox();
        colorLabel = new javax.swing.JLabel();
        colorChooserPanel = new javax.swing.JPanel();
        widthLabel = new javax.swing.JLabel();
        lineWidthSlider = new javax.swing.JSlider();
        isFilledRadioButton = new javax.swing.JRadioButton();
        canvas = new DrawingToolCanvas();

        setBorder(javax.swing.BorderFactory.createLineBorder(new Color(102, 0, 0)));
        setMinimumSize(new java.awt.Dimension(150, 150));
        setPreferredSize(new java.awt.Dimension(250, 250));
        setLayout(new java.awt.BorderLayout());

        toolSelectorPanel.setBackground(new Color(102, 0, 0));
        toolSelectorPanel.setMaximumSize(new java.awt.Dimension(999999999, 999999999));

        toolSelectorLabel.setForeground(new Color(255, 102, 0));
        toolSelectorLabel.setText("Tool:");
        toolSelectorLabel.setToolTipText("Tool Chooser Label");
        toolSelectorPanel.add(toolSelectorLabel);

        toolSelectorComboBox.setBackground(new Color(102, 0, 0));
        toolSelectorComboBox.setForeground(new Color(255, 102, 0));
        toolSelectorComboBox.setModel(new DefaultComboBoxModel<Tool>(DrawingToolStatus.getInstance().getToolList()));
        toolSelectorComboBox.setToolTipText("Tool Chooser ComboBox");
        toolSelectorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolSelectorComboBoxActionPerformed(evt);
            }
        });
        toolSelectorPanel.add(toolSelectorComboBox);

        colorLabel.setBackground(new Color(102, 0, 0));
        colorLabel.setForeground(new Color(255, 102, 0));
        colorLabel.setText("Color:");
        colorLabel.setToolTipText("Color Chooser Label");
        toolSelectorPanel.add(colorLabel);

        colorChooserPanel.setBackground(new Color(255, 102, 0));
        colorChooserPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(255, 102, 0)));
        colorChooserPanel.setToolTipText("Color Chooser Button");
        colorChooserPanel.setPreferredSize(new java.awt.Dimension(30, 20));
        colorChooserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorChooserPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorChooserPanelLayout = new javax.swing.GroupLayout(colorChooserPanel);
        colorChooserPanel.setLayout(colorChooserPanelLayout);
        colorChooserPanelLayout.setHorizontalGroup(
            colorChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorChooserPanelLayout.setVerticalGroup(
            colorChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        toolSelectorPanel.add(colorChooserPanel);

        widthLabel.setForeground(new Color(255, 102, 0));
        widthLabel.setText("Width: 2");
        widthLabel.setToolTipText("Current Line Width");
        toolSelectorPanel.add(widthLabel);

        lineWidthSlider.setBackground(new Color(102, 0, 0));
        lineWidthSlider.setForeground(new Color(255, 102, 0));
        lineWidthSlider.setMajorTickSpacing(10);
        lineWidthSlider.setMaximum(50);
        lineWidthSlider.setMinimum(1);
        lineWidthSlider.setMinorTickSpacing(5);
        lineWidthSlider.setPaintTicks(true);
        lineWidthSlider.setToolTipText("Line Width Slider");
        lineWidthSlider.setValue(2);
        lineWidthSlider.setPreferredSize(new java.awt.Dimension(100, 23));
        lineWidthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lineWidthSliderStateChanged(evt);
            }
        });
        toolSelectorPanel.add(lineWidthSlider);

        isFilledRadioButton.setBackground(new Color(102, 0, 0));
        isFilledRadioButton.setForeground(new Color(255, 102, 0));
        isFilledRadioButton.setText("Filled");
        isFilledRadioButton.setToolTipText("Fill Shape CheckBox");
        isFilledRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFilledRadioButtonActionPerformed(evt);
            }
        });
        toolSelectorPanel.add(isFilledRadioButton);

        add(toolSelectorPanel, java.awt.BorderLayout.PAGE_START);

        canvas.setBackground(new Color(255, 255, 255));
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                canvasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasMouseReleased(evt);
            }
        });
        canvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                canvasMouseDragged(evt);
            }
        });
        add(canvas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void toolSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolSelectorComboBoxActionPerformed
    Tool t = (Tool) toolSelectorComboBox.getSelectedItem();
    
    
    DrawingToolStatus dts = DrawingToolStatus.getInstance();
    
    dts.setCurrentTool(t);
    //added to avoid area under combobox not reappearing.
    dts.redrawCanvas();      
    repaint();
}//GEN-LAST:event_toolSelectorComboBoxActionPerformed

private void colorChooserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorChooserPanelMouseClicked
    DrawingToolStatus dts = DrawingToolStatus.getInstance();
    Color newColor = JColorChooser.showDialog(this, "Drawing Color", 
            dts.getCurrentColor());
    dts.setCurrentColor(newColor);
    colorChooserPanel.setBackground(dts.getCurrentColor());
    repaint();
}//GEN-LAST:event_colorChooserPanelMouseClicked

private void isFilledRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isFilledRadioButtonActionPerformed
    DrawingToolStatus.getInstance().setCurrentIsFilled(
            isFilledRadioButton.isSelected());
    repaint();
}//GEN-LAST:event_isFilledRadioButtonActionPerformed

private void canvasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseDragged
    DrawingToolStatus dts = DrawingToolStatus.getInstance();
    
    dts.getCurrentTool().performAction(evt.getPoint(), (Graphics2D)canvas.getGraphics());
    repaint();
}//GEN-LAST:event_canvasMouseDragged

private void canvasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseReleased
    DrawingToolStatus dts = DrawingToolStatus.getInstance();
    dts.getCurrentTool().mouseReleased((Graphics2D)canvas.getGraphics());
    repaint();
}//GEN-LAST:event_canvasMouseReleased

private void canvasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMousePressed
    DrawingToolStatus dts = DrawingToolStatus.getInstance();
    dts.getCurrentTool().performAction(evt.getPoint(), (Graphics2D)canvas.getGraphics());
    repaint();
}//GEN-LAST:event_canvasMousePressed

private void lineWidthSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lineWidthSliderStateChanged
    DrawingToolStatus.getInstance().setCurrentLineWidth(lineWidthSlider.getValue());
    widthLabel.setText("Width: " + lineWidthSlider.getValue());
    repaint();
}//GEN-LAST:event_lineWidthSliderStateChanged

    @Override
public void paintComponent(Graphics g){
    super.paintComponent(g);
    
    DrawingToolStatus dts = DrawingToolStatus.getInstance();
    
    //adjust toolselection bar for tooltype
    switch(dts.getCurrentToolType()) {
        case SHAPE_MAKER_TOOL:
            colorLabel.setVisible(true);
            colorChooserPanel.setVisible(true);
            isFilledRadioButton.setVisible(false);
            widthLabel.setVisible(true);
            lineWidthSlider.setVisible(true);
            break;
        case SHAPE_MAKER_TOOL_FILLABLE:
            colorLabel.setVisible(true);
            colorChooserPanel.setVisible(true);
            isFilledRadioButton.setVisible(true);
            widthLabel.setVisible(!isFilledRadioButton.isSelected());
            lineWidthSlider.setVisible(!isFilledRadioButton.isSelected());
            break;
        case MANIPULATOR_TOOL:
            colorLabel.setVisible(false);
            colorChooserPanel.setVisible(false);
            isFilledRadioButton.setVisible(false);
            widthLabel.setVisible(false);
            lineWidthSlider.setVisible(false);
            break;
        default: 
            break;     
    }
    
    if(dts.redrawCanvas())
            canvas.repaint();
         
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas;
    private javax.swing.JPanel colorChooserPanel;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JRadioButton isFilledRadioButton;
    private javax.swing.JSlider lineWidthSlider;
    private javax.swing.JComboBox toolSelectorComboBox;
    private javax.swing.JLabel toolSelectorLabel;
    private javax.swing.JPanel toolSelectorPanel;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables
}
